// Country cover photos (16-21 addendum): the fallback when a trip's
// destination is not a curated city but is in, or names, one of these
// countries (Nice, Bordeaux → France). Chosen by coverFor in ./cover.ts.
//
// Asmeen approved the 40 countries and every photo on 7 Oct 2026
// ("Approved as listed"; UAE beach: "Keep it"). Same rules as the cities:
// photographer, licence and source page are the Commons API values for each
// file (public-domain files link the licence to the file page, which carries
// the PD statement); CC0, CC BY or public domain only, no BY-SA. Focal points
// and alt text were set by looking at each photo. ISO alpha-2 codes are
// Wikidata P297; hemisphere is the sign of the country's Wikidata P625
// latitude; coastal = not a Wikidata "landlocked country". The approved
// candidate list with every source is 16-COUNTRY-CANDIDATES.md.
//
// Variants: one default photo; beach (used when the trip's interests include
// Beaches); season variants with the months Asmeen approved. Season months
// are northern-hemisphere months; the resolver shifts a southern trip's month
// by six before matching.
//
// Server-only, like the city manifest: import it from ./cover.ts only, so it
// never reaches client JavaScript. Files are made with
// scripts/photos/encode.mjs --out public/images/countries.

import { filesFor, type CoverPhoto } from './manifest'

export type CountryPhoto = CoverPhoto & {
  /** The beach variant, shown when the trip's interests include Beaches. */
  beach?: true
  /** A season variant for trips starting in these (northern-hemisphere) months. */
  season?: { name: 'winter' | 'spring' | 'summer' | 'autumn'; months: number[] }
}

export type Country = {
  /** ISO 3166-1 alpha-2, the same codes as GeoNames. */
  iso: string
  /** Display name, used on the credits page. */
  country: string
  /** Lowercase, accent-free names a destination can match (see normalizeCity). */
  names: string[]
  hemisphere: 'N' | 'S'
  coastal: boolean
  /** The default photo (no beach, no season) first. */
  photos: CountryPhoto[]
}

export const COUNTRIES: readonly Country[] = [
  {
    // Hemisphere: N (Wikidata Q45 P625 lat 38.7). Coastal: yes.
    iso: 'PT',
    country: 'Portugal',
    names: ['portugal'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'portugal',
        focal: { x: 0.5, y: 0.4 },
        alt: 'Pena Palace on its forested hilltop in Sintra, with the stone walls of the Moorish Castle on the ridge to the right',
        photographer: 'Jakub Hałun',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pal%C3%A1cio_Nacional_da_Pena,_Sintra,_Portugal,_20250606_1213_0172.jpg',
        files: filesFor('portugal', 'countries'),
        blur: 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoIAAUAAsBMJQBOgB5P3tAA/lv+uH1W2YYChBtjhcdnGuY0d5MIbCcXMIossOvtAE09JPAA',
      },
      {
        slug: 'portugal-beach',
        beach: true,
        focal: { x: 0.5, y: 0.55 },
        alt: 'Waves breaking on the rocky shore below golden limestone cliffs at Praia da Marinha in the Algarve, under a grey sky',
        photographer: 'erikccooper from Chicago, United Stats',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Praia_da_Marinha,_Lagoa,_Algarve_(48415167422).jpg',
        files: filesFor('portugal-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoIAAUAAsBMJQBOgCHHfhYAAPz/fe1K7OGN3rCX4kcZbG3K+fdb2+9SPoGVGYvnaZAAAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q29 P625 lat 40.2). Coastal: yes.
    iso: 'ES',
    country: 'Spain',
    names: ['spain', 'espana'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'spain',
        focal: { x: 0.5, y: 0.45 },
        alt: 'Towers and tiled roofs of the Alhambra in Granada among tall cypress trees, seen from the Generalife',
        photographer: 'Jebulon',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Roofs_and_towers_of_Alhambra_from_Generalife,_Granada,_Spain.jpg',
        files: filesFor('spain', 'countries'),
        blur: 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoIAAUAAsBMJQBOgCLKHbBguAD8AfczYRN+PBtoGEz0nantIcrS8fPz02gAAA==',
      },
      {
        slug: 'spain-beach',
        beach: true,
        focal: { x: 0.5, y: 0.45 },
        alt: 'Turquoise water in the small cove of Cala des Matzoc on Mallorca, with a pale stony shore and pine-covered hills',
        photographer: 'Olaf Tausch',
        licence: 'CC BY 3.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cala_des_Matzoc_06.jpg',
        files: filesFor('spain-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoIAAUAAsBMJZgCdAD0k6mUAAD4Y/QWofxCf1+hNFP2+aZqzMDAoT8Dwn4ZEZFYQcolWgAA',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q142 P625 lat 47). Coastal: yes.
    iso: 'FR',
    country: 'France',
    names: ['france'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'france',
        focal: { x: 0.5, y: 0.6 },
        alt: 'The abbey and village of Mont-Saint-Michel rising from the tidal flats under a cloudy sky',
        photographer: 'Giorgio Galeotti',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mont_Saint-Michel_-_Le_Mont-Saint-Michel,_France_-_August_14,_2018.jpg',
        files: filesFor('france', 'countries'),
        blur: 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAUAAsBMJZQCdADzesjgAP7q89qxU0n5ZChY3CZ6FthiCIbUTZT7wAA=',
      },
      {
        slug: 'france-beach',
        beach: true,
        focal: { x: 0.5, y: 0.5 },
        alt: "Plage de l'Escalet near Ramatuelle on the Côte d'Azur: a curve of white sand and clear blue sea, seen through dark shrubs",
        photographer: 'Francesco Cirigliano',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:La_C%C3%B4te_d%27Azur_(26060283833).jpg',
        files: filesFor('france-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoIAAUAAsBMJQBOgCL2sLu1AADifskAYFM1e/PX0qhAr9Wo4LbyT86R2VYgKcqU6W7bW4QhkGZBEkAA',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q145 P625 lat 54.6). Coastal: yes.
    iso: 'GB',
    country: 'United Kingdom',
    names: ['united kingdom', 'uk', 'great britain', 'britain', 'england'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'united-kingdom',
        focal: { x: 0.5, y: 0.55 },
        alt: "Derwentwater in the Lake District at dawn from Friars' Crag, with rocks in the still water and fells under a pink sky",
        photographer: 'Julian Herzog (Website)',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Derwentwater_Friars%27_Crag_Lake_District_2022_01.jpg',
        files: filesFor('united-kingdom', 'countries'),
        blur: 'data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACQAQCdASoIAAUAAsBMJZwAApepxIAA+WLnRxLbZmFZuhHtyPN3rHnkehQAAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q27 P625 lat 53). Coastal: yes.
    iso: 'IE',
    country: 'Ireland',
    names: ['ireland', 'eire'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'ireland',
        focal: { x: 0.5, y: 0.5 },
        alt: 'The Cliffs of Moher in Ireland lit by low sun above the Atlantic, with long grass in front',
        photographer: 'Elias Ehmann greene',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cliffs_of_Moher,_Ireland_(Unsplash_ndyYf_qU5Zk).jpg',
        files: filesFor('ireland', 'countries'),
        blur: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoIAAUAAsBMJQBOgCKUZqWOwAD7/8uw7iHLI+kZkeEdoCNcxb2/Ty5aGXiPzHeUAAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q55 P625 lat 52.3167). Coastal: yes.
    iso: 'NL',
    country: 'Netherlands',
    names: ['netherlands', 'the netherlands', 'holland'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'netherlands',
        focal: { x: 0.5, y: 0.45 },
        alt: 'Wooden windmills at Zaanse Schans in the Netherlands, with green meadows in front and a blue sky',
        photographer: 'DimiTalen',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Windmills_at_Zaanse_Schans,_Zaanstad,_2022.jpg',
        files: filesFor('netherlands', 'countries'),
        blur: 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoIAAUAAsBMJZACdAD0QV+MYAD+t7EUfxNK4n/j6aCSpo2DwADkmkSnzUoam4k0Y94AAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q183 P625 lat 51). Coastal: yes.
    iso: 'DE',
    country: 'Germany',
    names: ['germany', 'deutschland'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'germany',
        focal: { x: 0.5, y: 0.45 },
        alt: 'Neuschwanstein Castle on its forested crag in Bavaria, with a steep rock face behind it under a blue sky',
        photographer: 'Wilfredor',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Neuschwanstein_Castle_2024.jpg',
        files: filesFor('germany', 'countries'),
        blur: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoIAAUAAsBMJYwCdH8AFZ2IWAD94lvCAI9/i+CQKnzfB1iRieyYRrGA+zkLFGNAAAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q40 P625 lat 48). Coastal: no (landlocked, Wikidata P31 Q123480).
    iso: 'AT',
    country: 'Austria',
    names: ['austria', 'osterreich'],
    hemisphere: 'N',
    coastal: false,
    photos: [
      {
        slug: 'austria',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Hallstatt in winter: snow on the roofs of the lakeside houses and church, below steep snowy mountains',
        photographer: 'Haitao Zeng haitaoz',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hallstatt,_Austria_(Unsplash_rU2-7y7_dbo).jpg',
        files: filesFor('austria', 'countries'),
        blur: 'data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoIAAUAAsBMJZwCdAEO9sTIAP4mDmAdU8Z/CGsKEV0VATiTU75IAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q213 P625 lat 50). Coastal: no (landlocked, Wikidata P31 Q123480).
    iso: 'CZ',
    country: 'Czechia',
    names: ['czechia', 'czech republic'],
    hemisphere: 'N',
    coastal: false,
    photos: [
      {
        slug: 'czechia',
        focal: { x: 0.5, y: 0.6 },
        alt: 'Český Krumlov seen from the castle: red roofs of the old town along a bend of the Vltava, with a church tower and green hills beyond',
        photographer: 'Jakub Hałun',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:View_of_%C4%8Cesk%C3%BD_Krumlov_from_the_castle,_20250504_1305_8880.jpg',
        files: filesFor('czechia', 'countries'),
        blur: 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoIAAUAAsBMJZQAAubtFCoAAOIHx8nYz2qn4tuDBxzJ/7laA0+JMNiR7hAAAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q28 P625 lat 47). Coastal: no (landlocked, Wikidata P31 Q123480).
    iso: 'HU',
    country: 'Hungary',
    names: ['hungary'],
    hemisphere: 'N',
    coastal: false,
    photos: [
      {
        slug: 'hungary',
        focal: { x: 0.5, y: 0.5 },
        alt: 'The Hungarian Parliament Building lit up at dusk and reflected in the Danube',
        photographer: 'Pierre Blaché',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hungarian_Parliament_Building_2023-9.jpg',
        files: filesFor('hungary', 'countries'),
        blur: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoIAAUAAsBMJQBOilAAOqU3mvsAAP7c/Ft8C2Yyl/TXcT9f19rHxttC6aqKKJ+Yp8ZK4Hf1XNs2MjFEkMVQAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q38 P625 lat 42.5). Coastal: yes.
    iso: 'IT',
    country: 'Italy',
    names: ['italy', 'italia'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'italy',
        focal: { x: 0.5, y: 0.5 },
        alt: "A cypress-lined road winding through rolling fields in Val d'Orcia, Tuscany",
        photographer: 'kuhnmi',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Road_in_Val_d%27Orcia_(52682770061).jpg',
        files: filesFor('italy', 'countries'),
        blur: 'data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACQAQCdASoIAAUAAsBMJZQAAppim4AA/oQZnK7zdqUofOlvcLvEvAAA',
      },
      {
        slug: 'italy-beach',
        beach: true,
        focal: { x: 0.5, y: 0.5 },
        alt: 'Pastel houses of Positano stacked up the hillside on the Amalfi Coast, seen from a terrace with ceramic pots',
        photographer: 'Bernard Gagnon',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Positano_(Italy)_04.jpg',
        files: filesFor('italy-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoIAAUAAsBMJQBOgB5P38AAAP60JNhsyE/SS7EKT9VFRILx2iCQBdVoAAfCzrBfjlUYfHyCX0AAAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q35 P625 lat 56). Coastal: yes.
    iso: 'DK',
    country: 'Denmark',
    names: ['denmark', 'danmark'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'denmark',
        focal: { x: 0.5, y: 0.6 },
        alt: 'Colourful townhouses and old wooden ships along the Nyhavn canal in Copenhagen under a blue sky',
        photographer: 'Jebulon',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nyhavn_facades_Copenhagen_Denmark.jpg',
        files: filesFor('denmark', 'countries'),
        blur: 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoIAAUAAsBMJQBOgB5vWh8AAPqdB9+Cx3PlFDFnRdkKbxoNPiOJofmWQX/58XchaYP/m1c1D+ijyLHPgAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q34 P625 lat 61). Coastal: yes.
    iso: 'SE',
    country: 'Sweden',
    names: ['sweden', 'sverige'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'sweden',
        focal: { x: 0.5, y: 0.5 },
        alt: 'A red-trimmed wooden house among trees on a rocky shore of the Stockholm archipelago on a summer day',
        photographer: 'Bengt Nyman from Vaxholm, Sweden',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Archipelago_D81_4637_(48475152532).jpg',
        files: filesFor('sweden', 'countries'),
        blur: 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoIAAUAAsBMJYwCdAD0cgOAAP7Qyf46cMyc+kwL9Mn6iYF2iaZJ8hr0/5gxAAAA',
      },
      {
        slug: 'sweden-winter',
        season: { name: 'winter', months: [12, 1, 2, 3] },
        focal: { x: 0.5, y: 0.55 },
        alt: 'Green northern lights over a small wooden hut in Swedish Lapland at night',
        photographer: 'CangemiY',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Aurora_in_the_Swedish_Lapland_sky.jpg',
        files: filesFor('sweden-winter', 'countries'),
        blur: 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoIAAUAAsBMJQAAXOwkZaAA/vSxKAtQtPzrN1/HcPRr/WsVNq4QgAAA',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q20 P625 lat 59.9333). Coastal: yes.
    iso: 'NO',
    country: 'Norway',
    names: ['norway', 'norge'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'norway',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Bright green and pink northern lights over the mountains and sea at Flakstad in Lofoten, Norway',
        photographer: 'Johannes Groll followhansi',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lofoten,_Norway_(Unsplash).jpg',
        files: filesFor('norway', 'countries'),
        blur: 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoIAAUAAsBMJQBOj+ACuQso4AD+wp2G4JnvsluJGTSaxqzqlGvOgJ1OxQJ6Dg/WrxAAAA==',
      },
      {
        slug: 'norway-summer',
        season: { name: 'summer', months: [5, 6, 7, 8] },
        focal: { x: 0.5, y: 0.5 },
        alt: 'Boats leaving white wakes on the deep green water of Geirangerfjord in Norway',
        photographer: 'Lukas Beck',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Stranda_Geirangerfjord_lub_2025-07-29_img03.jpg',
        files: filesFor('norway-summer', 'countries'),
        blur: 'data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoIAAUAAsBMJQBOgCHfGbugAP73lzvXp6esMJgdgAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q33 P625 lat 65). Coastal: yes.
    iso: 'FI',
    country: 'Finland',
    names: ['finland', 'suomi'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'finland',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Sunset over the calm water of Lake Suvasvesi in Finland, with a dark line of forest on the far shore',
        photographer: 'Esaox',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sunset_at_lake_Suvasvesi,_Finland.jpg',
        files: filesFor('finland', 'countries'),
        blur: 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoIAAUAAsBMJZwCdEf/gbah/TAA4n3114Cv4K3+5YMKPPKR8bKLwAFAQVWmYJdUFSizS4AA',
      },
      {
        slug: 'finland-winter',
        season: { name: 'winter', months: [12, 1, 2, 3] },
        focal: { x: 0.5, y: 0.5 },
        alt: 'Tall snow-dusted pines seen from below against a pale winter sky in Finnish Lapland',
        photographer: 'Vincent Guth vingtcent',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Snowy_pines_in_Lapland_(Unsplash).jpg',
        files: filesFor('finland-winter', 'countries'),
        blur: 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoIAAUAAsBMJQBOgB6Q/0uAAM4+jikyqaA5KqRp4KdgixyGjR1zL2rSaSZf6AAA',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q189 P625 lat 65). Coastal: yes.
    iso: 'IS',
    country: 'Iceland',
    names: ['iceland'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'iceland',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Kirkjufell mountain above the Kirkjufellsfoss waterfall in Iceland, with a faint rainbow in a grey sky',
        photographer: 'Jakub Hałun',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kirkjufell,_Iceland,_20240714_1631_0713.jpg',
        files: filesFor('iceland', 'countries'),
        blur: 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoIAAUAAsBMJQAAXLWs2gAA/IwYhH3QevmTcmBp9lLWulQLBun7q95NTegAAA==',
      },
      {
        slug: 'iceland-winter',
        season: { name: 'winter', months: [11, 12, 1, 2, 3] },
        focal: { x: 0.5, y: 0.5 },
        alt: 'Green northern lights over a lit lighthouse on a snowy hill in Iceland at night',
        photographer: 'Sean O Riordan',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Aurora_Iceland.jpg',
        files: filesFor('iceland-winter', 'countries'),
        blur: 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoIAAUAAsBMJbACdADzesxgAP713f02hDzUvgoamtzkuA1k/xX5Mv0vCz+eT+rTvlnocoawWXAAAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q39 P625 lat 46.7986). Coastal: no (landlocked, Wikidata P31 Q123480).
    iso: 'CH',
    country: 'Switzerland',
    names: ['switzerland', 'schweiz', 'suisse', 'svizzera'],
    hemisphere: 'N',
    coastal: false,
    photos: [
      {
        slug: 'switzerland',
        focal: { x: 0.5, y: 0.5 },
        alt: 'The Matterhorn wrapped in cloud at sunset, with snow on its lower slopes and a pink and orange sky',
        photographer: 'Sam Ferrara samferrara',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Matterhorn_sunset_2016_(Unsplash).jpg',
        files: filesFor('switzerland', 'countries'),
        blur: 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoIAAUAAsBMJQBOgCLviVS2AAD9a35zZSf4GrCj68fJImbpQxx6/lMWq/v1WQdYpWkcrjpHJ/gAAA==',
      },
      {
        slug: 'switzerland-winter',
        season: { name: 'winter', months: [12, 1, 2, 3] },
        focal: { x: 0.5, y: 0.5 },
        alt: 'Winter in the valley near Zermatt: a village of wooden chalets in the snow below white Alpine peaks',
        photographer: 'Kosala Bandara from London, England',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Winter_in_Zermatt_(12150737134).jpg',
        files: filesFor('switzerland-winter', 'countries'),
        blur: 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoIAAUAAsBMJZQCdAEUo3nUQADMTSwtfmj9DuC6o0HA97mJO6tQ+1Rhpvz7xfTXkMAAAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q36 P625 lat 52). Coastal: yes.
    iso: 'PL',
    country: 'Poland',
    names: ['poland', 'polska'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'poland',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Morskie Oko lake in the Tatra Mountains of Poland, mirroring the sunlit peaks in the early morning',
        photographer: 'Aneta Pawska',
        licence: 'CC BY 3.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Morskie_Oko_o_poranku.jpg',
        files: filesFor('poland', 'countries'),
        blur: 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAUAAsBMJZQCdADze7UQAP7CUqTUrw5QcRCr2Dh+uDuyACZjWjaAAAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q224 P625 lat 45.25). Coastal: yes.
    iso: 'HR',
    country: 'Croatia',
    names: ['croatia', 'hrvatska'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'croatia',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Waterfalls, green pools and a wooden boardwalk at Plitvice Lakes National Park in Croatia',
        photographer: 'Clara Delormeau claradel',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Plitvice_Lakes_National_Park_(Unsplash).jpg',
        files: filesFor('croatia', 'countries'),
        blur: 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoIAAUAAsBMJQBdgCHM/jvAAP7Q+ufNtf60L/vGemA2VZTmQAdOfrU5aQAAAA==',
      },
      {
        slug: 'croatia-beach',
        beach: true,
        focal: { x: 0.5, y: 0.6 },
        alt: 'Turquoise water in Stiniva cove on the island of Vis, Croatia, enclosed by tall white cliffs, with swimmers in the bay',
        photographer: 'dronepicr',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Schwimmbereich_an_der_Bucht_Stiniva_auf_Vis,_Kroatien_(48694022267).jpg',
        files: filesFor('croatia-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoIAAUAAsBMJQBOj+ADGFEBk+QA88xsU1sdWHxXu9hLBrOz2YG3n7AB5susjBA5fa3Xiab8oAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q41 P625 lat 38.5). Coastal: yes.
    iso: 'GR',
    country: 'Greece',
    names: ['greece', 'hellas'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'greece',
        focal: { x: 0.5, y: 0.55 },
        alt: 'White houses and a small pool on the clifftop at Oia, Santorini, above the deep blue Aegean',
        photographer: 'Mariamichelle',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Santorini_Oia_Greece_Travel_Summer_Greek_Island.jpg',
        files: filesFor('greece', 'countries'),
        blur: 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoIAAUAAsBMJZACdADze7UQAPvyyYVFCvcjgkMng27IINhSQZu6IKBz/d4mtlgm8DWzkAChtTegY3AA',
      },
      {
        slug: 'greece-beach',
        beach: true,
        focal: { x: 0.5, y: 0.55 },
        alt: 'Navagio Beach on Zakynthos from the clifftop, with the shipwreck on the white sand and boats in the turquoise water',
        photographer: 'dronepicr',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Navagio_Beach_and_wreck_of_the_MV_Panagiotis_(31530077597).jpg',
        files: filesFor('greece-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoIAAUAAsBMJbACdAEekKZFTAAAziMSDDYNbHjI7+cH8Hh0W4anOQ2voTYAN17939xsu5zor605dPW/XJjxV10AAAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q43 P625 lat 39). Coastal: yes.
    iso: 'TR',
    country: 'Turkey',
    names: ['turkey', 'turkiye'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'turkey',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Hot-air balloons drifting over the rock formations and valleys of Cappadocia around Göreme',
        photographer: 'prilfish',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ballooning_in_and_around_G%C3%B6reme.jpg',
        files: filesFor('turkey', 'countries'),
        blur: 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoIAAUAAsBMJYwCdAEOPB2+AADN89nEzcjTMDlrkRKt/5pCMZi+hG1nwkyAAA==',
      },
      {
        slug: 'turkey-beach',
        beach: true,
        focal: { x: 0.5, y: 0.55 },
        alt: "Pine-covered hills sloping down to the bay at Ölüdeniz on Turkey's south-west coast under a hazy sky",
        photographer: 'dronepicr',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Blick_%C3%BCber_den_%C3%96l%C3%BCdeniz_Bucht,_T%C3%BCrkei_(49070957592).jpg',
        files: filesFor('turkey-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoIAAUAAsBMJQBOgCHe8CTwAPz8JbjqaWWM4NEt+dAngzkyeI2uGynlUxE2vwAA',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q1028 P625 lat 32). Coastal: yes.
    iso: 'MA',
    country: 'Morocco',
    names: ['morocco'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'morocco',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Rippled orange sand dunes near Merzouga in the Moroccan Sahara',
        photographer: 'Mustang Joe',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Merzouga_dunes_of_Morocco.jpg',
        files: filesFor('morocco', 'countries'),
        blur: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoIAAUAAsBMJZgCdAD0eqqyAAD+0Jgf8azXIBbBZNmhYviBrWImw8j/kVuxOf4AAAA=',
      },
      {
        slug: 'morocco-beach',
        beach: true,
        focal: { x: 0.5, y: 0.45 },
        alt: "A blue fishing boat on the shore in front of the white houses of Taghazout on Morocco's Atlantic coast",
        photographer: 'Dr. Matthias Ripp',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Taghazout_Beach1.jpg',
        files: filesFor('morocco-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoIAAUAAsBMJZACdAEfbkLPg4AA/rI/yAHjnRgPrqWBI61ZLuu3Gid+Ta6Kb0GEYuDxURcNvSAAAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q79 P625 lat 27). Coastal: yes.
    iso: 'EG',
    country: 'Egypt',
    names: ['egypt'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'egypt',
        focal: { x: 0.5, y: 0.55 },
        alt: 'The Pyramids of Giza under a clear sky, with three smaller pyramids in front',
        photographer: 'Mustang Joe',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Pyramids_of_Giza_(53613732878).jpg',
        files: filesFor('egypt', 'countries'),
        blur: 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoIAAUAAsBMJagCdAEef/xCwADiNmFKmCow6pQ9nGKwNN0zHE1XGcInxvdffNA1S96u4AAA',
      },
      {
        slug: 'egypt-beach',
        beach: true,
        focal: { x: 0.5, y: 0.55 },
        alt: 'A small arched lookout on the sandy Red Sea shore near Port Ghalib, Marsa Alam, beside a large rock',
        photographer: 'Marc Ryckaert (MJJR)',
        licence: 'CC BY 3.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Marsa_Alam_R08.jpg',
        files: filesFor('egypt-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAAUAAsBMJYgCdAEO94DkAAD8ywxP8OaToxGoyaTdN889NSld5AAA',
      },
    ],
  },
  {
    // Hemisphere: S (Wikidata Q258 P625 lat -29). Coastal: yes.
    iso: 'ZA',
    country: 'South Africa',
    names: ['south africa'],
    hemisphere: 'S',
    coastal: true,
    photos: [
      {
        slug: 'south-africa',
        focal: { x: 0.5, y: 0.4 },
        alt: 'The Three Rondavels and the cliffs of Blyde River Canyon in South Africa, framed by tree branches under a cloudy sky',
        photographer: 'Bernard Barsalo from Kirkland, Canada',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Trois_Rondavels_-_Three_Rondavels_View_Point_-_Blyde_River_Canyon_-_Flickr_-_(bbarsalo).jpg',
        files: filesFor('south-africa', 'countries'),
        blur: 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoIAAUAAsBMJQBOgB5vdzEAAP7RtgtAh7XXpfE+lZH1XdkDGLNcoWAQzttbhbUzZNIhIIAA',
      },
      {
        slug: 'south-africa-beach',
        beach: true,
        focal: { x: 0.5, y: 0.5 },
        alt: 'Granite boulders and clear turquoise water at Boulders Beach near Cape Town, South Africa',
        photographer: 'jeffgreenca',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Boulders_Beach,_South_Africa.jpg',
        files: filesFor('south-africa-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAgCdASoIAAUAAsBMJZgCdGuAAoeiiAQAAMyitFUjBKgz+ArMjvBwXOyGwvnfYl0Vc+gxAAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q878 P625 lat 24.4). Coastal: yes.
    iso: 'AE',
    country: 'United Arab Emirates',
    names: ['united arab emirates', 'uae'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'united-arab-emirates',
        focal: { x: 0.5, y: 0.55 },
        alt: 'Sand dunes with scattered green shrubs in the Liwa desert of the United Arab Emirates under a pale sky',
        photographer: 'greeeen2008',
        licence: 'CC BY 3.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liwa_%D8%B7%D8%B1%D9%8A%D9%82_%D8%AA%D9%84_%D8%A7%D9%84%D9%85%D8%B1%D8%B9%D8%A8_-_panoramio_-_greeeen2008_(3).jpg',
        files: filesFor('united-arab-emirates', 'countries'),
        blur: 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoIAAUAAsBMJQBOgCHhipgmAAD33+fgbP6Rxg1+l0NoK8NMmgao+OR0AAA=',
      },
      {
        slug: 'united-arab-emirates-beach',
        beach: true,
        focal: { x: 0.5, y: 0.5 },
        alt: "Dubai Marina beach in evening light, with tall towers behind the sand and a person walking along the water's edge",
        photographer: 'kishjar? from Moscow, Russia',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Dubai_Marina_beach_(54865809126).jpg',
        files: filesFor('united-arab-emirates-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAUAAsBMJQBOgCKTPunAAP2/HQglyZG4xYkHJMAvGedtzypulzeQAAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q668 P625 lat 22.8). Coastal: yes.
    iso: 'IN',
    country: 'India',
    names: ['india'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'india',
        focal: { x: 0.5, y: 0.55 },
        alt: 'The Taj Mahal in Agra with its four minarets, seen past the long reflecting pool and cypress-lined gardens',
        photographer: 'Almbauer',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Taj_Mahal_2018.jpg',
        files: filesFor('india', 'countries'),
        blur: 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoIAAUAAsBMJQBOgBujC3AAAPd9pkHgmnxYu53ASE+Ug8T/m9u5r0oA',
      },
      {
        slug: 'india-beach',
        beach: true,
        focal: { x: 0.5, y: 0.45 },
        alt: 'Palolem Beach in Goa in golden light: a curve of sand and waves backed by palm trees and beach huts',
        photographer: 'Nico Crisafulli from USA',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Palolem_Beach_(5580920479).jpg',
        files: filesFor('india-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoIAAUAAsBMJQBOiP/wP8GsuRAA/rd1pBBq596cMdOjde5XXK/xxgjbvI4uuCRGFywXaoYtQFLAAA==',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q869 P625 lat 14). Coastal: yes.
    iso: 'TH',
    country: 'Thailand',
    names: ['thailand'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'thailand',
        focal: { x: 0.5, y: 0.45 },
        alt: 'The central tower of Wat Chaiwatthanaram in Ayutthaya, with gold-robed Buddha statues on its brick base and smaller towers around it',
        photographer: 'Evilarry',
        licence: 'Public domain',
        licenceUrl: 'https://commons.wikimedia.org/wiki/File:Ayutthaya_Thailand_2004.jpg',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ayutthaya_Thailand_2004.jpg',
        files: filesFor('thailand', 'countries'),
        blur: 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAgCdASoIAAUAAsBMJYgCdH8IwABQ7uRqAAD7mf3nXCb1eOsbI3FeASPI02mC2FakrF7BV+nOSxBmzwAAAA==',
      },
      {
        slug: 'thailand-beach',
        beach: true,
        focal: { x: 0.5, y: 0.55 },
        alt: 'A limestone cliff and long-tail boats on the sea at Maya Bay, Thailand, under a pink evening sky',
        photographer: 'Alexey Komarov',
        licence: 'CC BY 3.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Maya_Bay_-_panoramio.jpg',
        files: filesFor('thailand-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoIAAUAAsBMJZQAApZCFgAA/sK940S7jTdVDggFyl/KEYqPKNijgAAA',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q881 P625 lat 16). Coastal: yes.
    iso: 'VN',
    country: 'Vietnam',
    names: ['vietnam', 'viet nam'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'vietnam',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Tall limestone islands rising from the calm water of Hạ Long Bay in Vietnam',
        photographer: 'Mustang Joe',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:H%E1%BA%A1_Long_Bay,_Vietnam_1.jpg',
        files: filesFor('vietnam', 'countries'),
        blur: 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoIAAUAAsBMJZQCdADze7hYAP4nY1el8npdp6/KVgHRIpR1fIZWCEA7+CqQAA==',
      },
      {
        slug: 'vietnam-beach',
        beach: true,
        focal: { x: 0.5, y: 0.45 },
        alt: 'A long wooden pier stretching into the calm sea off Phu Quoc Island, Vietnam, under a golden sky and heavy clouds',
        photographer: 'Quangpraha',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Phu_Quoc_Island_01.jpg',
        files: filesFor('vietnam-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAUAAsBMJZQCdADZkPFAAPuZ4GtEraJoY3aqUOupv5hiCQadDdQNAAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q334 P625 lat 1.3). Coastal: yes.
    iso: 'SG',
    country: 'Singapore',
    names: ['singapore'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'singapore',
        focal: { x: 0.5, y: 0.5 },
        alt: 'The Supertree Grove at Gardens by the Bay in Singapore, seen from above among green trees',
        photographer: 'Mustang Joe',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Supertree_Grove,_Gardens_by_the_Bay,_Singapore1.jpg',
        files: filesFor('singapore', 'countries'),
        blur: 'data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoIAAUAAsBMJZQCdAEDpBjC8AD+7Pw5blvX2m5mUXcXOHyJsGgAAA==',
      },
    ],
  },
  {
    // Hemisphere: S (Wikidata Q252 P625 lat -2). Coastal: yes.
    iso: 'ID',
    country: 'Indonesia',
    names: ['indonesia'],
    hemisphere: 'S',
    coastal: true,
    photos: [
      {
        slug: 'indonesia',
        focal: { x: 0.5, y: 0.5 },
        alt: 'The Tegallalang rice terraces in Bali, with palm trees growing between the stepped paddies',
        photographer: 'Philip Nalangan',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tegallalang_Rice_Terraces_Bali.jpg',
        files: filesFor('indonesia', 'countries'),
        blur: 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAAUAAsBMJZgCdAD5af/GAAD7+w14Ye0JCmcmNamIveRVvndyOAAA',
      },
      {
        slug: 'indonesia-beach',
        beach: true,
        focal: { x: 0.5, y: 0.5 },
        alt: 'Padar Island in Komodo National Park, Indonesia, with curving bays of sand and blue water between dry hills',
        photographer: 'Jakub Hałun',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Padar_Island,_Komodo_National_Park,_Indonesia,_20250822_0929_2659.jpg',
        files: filesFor('indonesia-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoIAAUAAsBMJQBOgCHXYJAAAPZHqwQ2v7TSTrJN+iNvHXHRovFm0/SRCyEw+UpMAAA=',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q17 P625 lat 35). Coastal: yes.
    iso: 'JP',
    country: 'Japan',
    names: ['japan'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'japan',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Snow-capped Mount Fuji at sunset across a calm lake, under a blue and pink sky',
        photographer: 'Romain Guy from San Francisco, USA',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mount_Fuji_at_sunset,_March_2025.jpg',
        files: filesFor('japan', 'countries'),
        blur: 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoIAAUAAsBMJYgCdAEO3siYFAAA+N4FH9xWhFmnlxpDPPUKIPuPFY5CEMmHsdYdFAAAAA==',
      },
      {
        slug: 'japan-beach',
        beach: true,
        focal: { x: 0.5, y: 0.45 },
        alt: 'Clear turquoise water and glass-bottom boats in Kabira Bay on Ishigaki Island, Okinawa',
        photographer: '663highland',
        licence: 'CC BY 2.5',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.5',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kabira_Bay_Ishigaki_Island40bs3s4592.jpg',
        files: filesFor('japan-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoIAAUAAsBMJagCdAEOO/CwAPz8BNb896bfXXpsF//ZlFFH/sSVd2rT7LEoAA==',
      },
      {
        slug: 'japan-autumn',
        season: { name: 'autumn', months: [10, 11] },
        focal: { x: 0.5, y: 0.45 },
        alt: 'Birches and red and yellow autumn leaves reflected in a pond at Shiga Kōgen, Nagano',
        photographer: 'Akiko_Toshinai',
        licence: 'CC BY 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nagano-Autumn_leaves-xl.jpg',
        files: filesFor('japan-autumn', 'countries'),
        blur: 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoIAAUAAsBMJbACdADze7UQAMoK5PLM8UMdf2JX+Lfg37IsX5HghPP2G/AAAA==',
      },
      {
        slug: 'japan-spring',
        season: { name: 'spring', months: [3, 4] },
        focal: { x: 0.5, y: 0.5 },
        alt: 'Himeji Castle beyond cherry blossoms and pruned pines on a sunny spring day',
        photographer: 'Loggieloggie',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Himeji_Castle_20260403120700.jpg',
        files: filesFor('japan-spring', 'countries'),
        blur: 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoIAAUAAsBMJaACdGuAAsyRgcAAzfFI+/1ge0/mMWAOfZ93PhTb/dqTwekX9JAA',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q884 P625 lat 36). Coastal: yes.
    iso: 'KR',
    country: 'South Korea',
    names: ['south korea', 'korea'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'south-korea',
        focal: { x: 0.5, y: 0.5 },
        alt: 'A rocky mountain stream with clear green pools among granite boulders in Seoraksan National Park, South Korea',
        photographer: 'lumoplank',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Seoraksan-_Part_I_-_Seoraksan3390.jpg',
        files: filesFor('south-korea', 'countries'),
        blur: 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoIAAUAAsBMJYgCdADze0owAP5BB3X3SpPmuYj4n8wPgGvjYU1X8ExPJLqZ78AA',
      },
    ],
  },
  {
    // Hemisphere: S (Wikidata Q408 P625 lat -25). Coastal: yes.
    iso: 'AU',
    country: 'Australia',
    names: ['australia'],
    hemisphere: 'S',
    coastal: true,
    photos: [
      {
        slug: 'australia',
        focal: { x: 0.5, y: 0.75 },
        alt: 'Limestone stacks of the Twelve Apostles off the cliffs of the Great Ocean Road in Victoria, Australia, under a cloudy sky',
        photographer: 'Dhruva Reddy dvxry',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Twelve_Apostles,_Princetown_(Unsplash).jpg',
        files: filesFor('australia', 'countries'),
        blur: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoIAAUAAsBMJZACdAEOZ/HeAP7z8TvPd0KyNq9S/LR/AvCapUkYbJJXVhjlC4OMAAA=',
      },
      {
        slug: 'australia-beach',
        beach: true,
        focal: { x: 0.6, y: 0.5 },
        alt: 'Wineglass Bay in Tasmania: orange-lichened granite rocks in front of clear water and a curving white beach below the hills',
        photographer: 'Phil Whitehouse from London, United Kingdom',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wineglass_Bay_(29602509684).jpg',
        files: filesFor('australia-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoIAAUAAsBMJZwAAuab37gA/Nc24xMToAHzgdo49iO481pZgAA=',
      },
    ],
  },
  {
    // Hemisphere: S (Wikidata Q664 P625 lat -41.2). Coastal: yes.
    iso: 'NZ',
    country: 'New Zealand',
    names: ['new zealand', 'aotearoa'],
    hemisphere: 'S',
    coastal: true,
    photos: [
      {
        slug: 'new-zealand',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Steep misty cliffs and a thin waterfall dropping into Milford Sound, New Zealand',
        photographer: 'Bengt Nyman',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Milford_Sound_NZ7_2785.jpg',
        files: filesFor('new-zealand', 'countries'),
        blur: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoIAAUAAsBMJaACdAEWUM4csAD+5ug14c6wdA2GCXyBukQPaQ9uDQYUnLOb8hRQAAA=',
      },
      {
        slug: 'new-zealand-beach',
        beach: true,
        focal: { x: 0.5, y: 0.45 },
        alt: 'Wharariki Beach in New Zealand with the Archway Islands offshore and dune grass in front',
        photographer: 'Pseudopanax at English Wikipedia',
        licence: 'Public domain',
        licenceUrl: 'https://commons.wikimedia.org/wiki/File:Wharariki_Beach_and_Archway_Islands.jpg',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wharariki_Beach_and_Archway_Islands.jpg',
        files: filesFor('new-zealand-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoIAAUAAsBMJQBdj+ADE2iRPwAA/tYqssjDCMBZTlRebE8+iqYPTIuiDZKNywAA',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q30 P625 lat 39.8282). Coastal: yes.
    iso: 'US',
    country: 'United States',
    names: ['united states', 'united states of america', 'usa', 'america'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'united-states',
        focal: { x: 0.5, y: 0.5 },
        alt: 'Horseshoe Bend, where the green Colorado River loops around a sandstone outcrop near Page, Arizona',
        photographer: 'Christian Mehlführer, User:Chmehl',
        licence: 'CC BY 2.5',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.5',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Grand_Canyon_Horse_Shoe_Bend_MC.jpg',
        files: filesFor('united-states', 'countries'),
        blur: 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoIAAUAAsBMJYgCdADyfv4AAP6I+rx97bXy8xvmRNJSXoBxSZmISFr6MNXDomO+bquQeIAAAAA=',
      },
      {
        slug: 'united-states-beach',
        beach: true,
        focal: { x: 0.5, y: 0.45 },
        alt: 'Turquoise water off Lanikai on Oʻahu, Hawaii, seen from the hills above the palm-lined neighbourhood',
        photographer: 'Raita Futo from Tokyo, Japan',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lanikai_seascape_(53312899066).jpg',
        files: filesFor('united-states-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoIAAUAAsBMJYgCdEf/gcFCpjUAAM1t7iJWTYSy019zBzsRcvEMMB60idZNjSXGNx6CIAAA',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q16 P625 lat 56). Coastal: yes.
    iso: 'CA',
    country: 'Canada',
    names: ['canada'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'canada',
        focal: { x: 0.5, y: 0.45 },
        alt: 'Lake Agnes in Banff National Park, Canada, reflecting grey peaks and green forested slopes',
        photographer: 'Florian Fuchs',
        licence: 'CC BY 3.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lake_Agnes_im_Banff_National_Park.jpg',
        files: filesFor('canada', 'countries'),
        blur: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoIAAUAAsBMJZQCdADze7hYAP7CcuP8h8T0o1F3zmfx8BRToroMkn4Q3DABVCiOYAA=',
      },
      {
        slug: 'canada-autumn',
        season: { name: 'autumn', months: [9, 10] },
        focal: { x: 0.5, y: 0.55 },
        alt: 'Golden autumn aspens and dark pines above a valley in Kananaskis, Alberta, with mountains behind',
        photographer: 'Thank you for visiting my page from Canada',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kananaskis_Fall_colours_(21833757516).jpg',
        files: filesFor('canada-autumn', 'countries'),
        blur: 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoIAAUAAsBMJbACdGuAAvpz6bWAAP5hb9PP9UsUjFwrgMcDpSEEpsxTmvG6846VwDJiH2S9iQz9gAAA',
      },
    ],
  },
  {
    // Hemisphere: N (Wikidata Q96 P625 lat 23). Coastal: yes.
    iso: 'MX',
    country: 'Mexico',
    names: ['mexico'],
    hemisphere: 'N',
    coastal: true,
    photos: [
      {
        slug: 'mexico',
        focal: { x: 0.5, y: 0.45 },
        alt: 'El Castillo, the stepped pyramid of Chichén Itzá, on a green lawn with visitors in front under a cloudy sky',
        photographer: 'Álvaro de la Paz Franco',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Chich%C3%A9n_Itz%C3%A1_-_Castillo_y_alrededores_01.jpg',
        files: filesFor('mexico', 'countries'),
        blur: 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoIAAUAAsBMJbAAAppHRbAA/uGr6D0E/v1E/lAgULh1MFot8LUXPzf9iJBV4dsOL58RhsAA',
      },
      {
        slug: 'mexico-beach',
        beach: true,
        focal: { x: 0.5, y: 0.5 },
        alt: 'A white sand beach with sun loungers and palm trees beside turquoise Caribbean water on Isla Mujeres, Mexico',
        photographer: 'dronepicr',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Beaches_of_Isla_Mujeres_Mexico_(29729632218).jpg',
        files: filesFor('mexico-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoIAAUAAsBMJbACdADze7mIAM3xmZ/E28noU0REER5EM3CGeBrk7pQHIfJ0ibe6Su4y+1jDCAA=',
      },
    ],
  },
  {
    // Hemisphere: S (Wikidata Q155 P625 lat -14). Coastal: yes.
    iso: 'BR',
    country: 'Brazil',
    names: ['brazil', 'brasil'],
    hemisphere: 'S',
    coastal: true,
    photos: [
      {
        slug: 'brazil',
        focal: { x: 0.5, y: 0.6 },
        alt: 'White sand dunes of Lençóis Maranhenses National Park in Brazil stretching to the horizon under a blue sky',
        photographer: 'Otávio Nogueira from Fortaleza, BR',
        licence: 'CC BY 2.0',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Parque_Nacional_dos_Len%C3%A7%C3%B3is_Maranhenses,-3_(53241759010).jpg',
        files: filesFor('brazil', 'countries'),
        blur: 'data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoIAAUAAsBMJZQCdH8AFbMU3AAA/phaznYmCL3vQAKBXv1GTwAAAA==',
      },
      {
        slug: 'brazil-beach',
        beach: true,
        focal: { x: 0.5, y: 0.5 },
        alt: 'Morro Dois Irmãos rising from the sea beyond Cacimba do Padre beach on Fernando de Noronha, Brazil, with waves on the sand',
        photographer: 'Rosana Antunes',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Praia_paradis%C3%ADaca_em_Fernando_de_Noronha.jpg',
        files: filesFor('brazil-beach', 'countries'),
        blur: 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoIAAUAAsBMJZQCdAD5gPvLYAD+yoCm2YAZwTkTj0pFYewmxXOBQbSNxAIv8QvJmbAAAA==',
      },
    ],
  },
  {
    // Hemisphere: S (Wikidata Q419 P625 lat -9.4). Coastal: yes.
    iso: 'PE',
    country: 'Peru',
    names: ['peru'],
    hemisphere: 'S',
    coastal: true,
    photos: [
      {
        slug: 'peru',
        focal: { x: 0.5, y: 0.45 },
        alt: "Machu Picchu's terraces and stone ruins on a green ridge, seen from Huayna Picchu above a steep valley",
        photographer: 'Martin St-Amant (S23678)',
        licence: 'CC BY 2.5',
        licenceUrl: 'https://creativecommons.org/licenses/by/2.5',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mosaique_du_Machu_Picchu_depuis_le_Huayna_Picchu.jpg',
        files: filesFor('peru', 'countries'),
        blur: 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoIAAUAAsBMJQBdgCLvkW81L4AAziJon2UX7NIQlP2DdYLftLwzr0icAAA=',
      },
    ],
  },
  {
    // Hemisphere: S (Wikidata Q414 P625 lat -34). Coastal: yes.
    iso: 'AR',
    country: 'Argentina',
    names: ['argentina'],
    hemisphere: 'S',
    coastal: true,
    photos: [
      {
        slug: 'argentina',
        focal: { x: 0.5, y: 0.5 },
        alt: 'The ice wall of the Perito Moreno Glacier meeting turquoise lake water, with dark mountains behind, in Patagonia, Argentina',
        photographer: 'Patrícia Cassol Pereira pcpereira',
        licence: 'CC0',
        licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Perito_Moreno_Glacier,_Argentina_(Unsplash_L9RtyL_hzUg).jpg',
        files: filesFor('argentina', 'countries'),
        blur: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoIAAUAAsBMJZgCdADyfv4AAPqfDvog1Fv2oPwCFbFgDBFr3ySISxn3Wqqexeu4AAA=',
      },
    ],
  },
]
